services:
  frontend:
    image: mousearthouse/rar-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend

  backend:
    image: mousearthouse/rar-backend:latest
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgres://myuser:secret@db:5432/rar
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: rar
    ports:
      - "5430:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
