services:
  frontend:
    image: mousearthouse/rar-frontend:latest
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
    - /home/mouse/nginx/certs:/etc/nginx/certs:ro

  backend:
    image: mousearthouse/rar-backend:latest
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5430:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
