name: Mouse-flow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  backend:
    runs-on: self-hosted
    if: "contains(github.event.head_commit.modified, 'backend/')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull origin main

      - name: Build & Deploy Backend
        run: |
          cd backend
          docker build -t mousearthouse/rar-backend:latest .
          cd ..
          docker-compose up -d

  frontend:
    runs-on: self-hosted
    if: "contains(github.event.head_commit.modified, 'frontend/')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull latest changes
        run: git pull origin main

      - name: Build & Deploy Frontend
        run: |
          cd frontend
          docker build -t mousearthouse/rar-frontend:latest .
          cd ..
          docker-compose up -d
